### ISSUE TITLE
定位失败，此key每日调用量已达到上限，将显示默认的广东广州天气

### ISSUE THREAD

**Issue by lqx131499** [hjiachuang/vue3-mini-weather#2]
定位失败，此key每日调用量已达到上限，将显示默认的广东广州天气

![image](https://github.com/hjiachuang/vue3-mini-weather/assets/8575432/98cf4942-1152-488b-a91a-2a5b61e449de)

作者的key调用量已满，能否让用户自定义key来使用？

**Comment by EchoShoot** [comment]
遇到同样问题+1，这个天气api背后调用的是哪家的？我自己去申请一下？

**Comment by lqx131499** [comment]
你的邮件我已收到，谢谢。如有必要，请联系：13794627738

**Comment by EchoShoot** [comment]
> 你的邮件我已收到，谢谢。如有必要，请联系：13794627738
我看了下项目的说明，这个项目与另一个项目是同步的，以另一个项目为主。那个项目提供了接口的部署，需要自己去申请一个 key，然后把它启动起来，这样就是用着自己的key数量了
https://github.com/hjiachuang/vue-mini-weather/tree/master/php/weather

**Comment by lqx131499** [comment]
> > 你的邮件我已收到，谢谢。如有必要，请联系：13794627738
> > 我看了下项目的说明，这个项目与另一个项目是同步的，以另一个项目为主。那个项目提供了接口的部署，需要自己去申请一个 key，然后把它启动起来，这样就是用着自己的key数量了
> > https://github.com/hjiachuang/vue-mini-weather/tree/master/php/weather

谢谢，帮了大忙了，解决了
